---
version: "3.8"
services:
  myjenkins:
    image: jenkins/jenkins
    ports: 
      - 8080:8080
  qaserver:
    image: tomee
    ports: 
      - 9090:80
    links:
      - myjenkins:jenkins
  prodserver:
    image: tomee
    ports: 
      - 7070:80
    links:
      - myjenkins:jenkins
...
