version: '3.8'
services:
  hub:
    image: selenium/hub
    ports:
      - 4444:4444
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: "100M"
      placement:
        constraints:
