---
version: '3.8'
services:
  mydb:
    image: postgres
    environment:
      POSTGRES_USER_FILE: /run/secret/pg_user
      POSTGRES_PASSWORD_FILE: /run/secret/pg_password
      POSTGRES_DB_FILE: /run/secret/pg_db
    secrets:
      - pg_user
      - pg_password
      - pg_db
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.hostname == worker1
    resources:
      limit:
        cpus: "0.01"
        memory: "100M"

  mydminer:
    image: adminer
    ports:
      - 8080:8080
    deploy:
      replicas: 3
    resources:
      limit:
        cpus: "0.01"
        memory: "50M"
    volumes:
      - v1:/var/lib/postgresql/data


volumes:
  v1:

secrets:
  pg_user:
    external: true
  pg_password:
    external: true
  pg_db:
    external: true

...
